const BASE='https://api.chess.com/pub/player';
const charts={}, detailCharts={};
const DRAW_RESULTS=new Set(['agreed','repetition','stalemate','timevsinsufficient','insufficient','50move']);
const fmtPct=n=>`${(n*100).toFixed(1)}%`;
const byMonthKey=t=>{const d=new Date(t*1000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`};
const daysAgoTs=d=>Math.floor((Date.now()-d*86400000)/1000);
const getFilterStart=f=>f==='24h'?daysAgoTs(1):f==='7d'?daysAgoTs(7):f==='30d'?daysAgoTs(30):f==='90d'?daysAgoTs(90):0;

const engineState={worker:null,ready:false,queue:[],nextId:1,pending:new Map()};
function initEngine(){if(engineState.worker) return;engineState.worker=new Worker('https://cdn.jsdelivr.net/npm/stockfish.js@10.0.2/stockfish.js');engineState.worker.onmessage=(e)=>onEngineMsg(String(e.data||''));engineState.worker.postMessage('uci');engineState.worker.postMessage('isready');}
function onEngineMsg(line){if(line==='readyok'){engineState.ready=true;flushEngine();return;}if(line.startsWith('info')&&line.includes(' score ')){const id=[...engineState.pending.keys()][0];if(!id) return;const p=engineState.pending.get(id);p.last=line;return;}if(line.startsWith('bestmove')){const id=[...engineState.pending.keys()][0];if(!id) return;const p=engineState.pending.get(id);engineState.pending.delete(id);p.resolve(scoreFromInfo(p.last));flushEngine();}}
function scoreFromInfo(info){if(!info) return 0;const m=info.match(/score (cp|mate) (-?\d+)/);if(!m) return 0; if(m[1]==='cp') return Math.max(-1000,Math.min(1000,Number(m[2]))); const mate=Number(m[2]); return mate>0?1000:-1000;}
function flushEngine(){if(!engineState.ready||engineState.pending.size||!engineState.queue.length) return;const q=engineState.queue.shift();engineState.pending.set(q.id,q);engineState.worker.postMessage(`position fen ${q.fen}`);engineState.worker.postMessage('go depth 12');}
function evalFen(fen){initEngine();return new Promise(resolve=>{engineState.queue.push({id:engineState.nextId++,fen,resolve,last:''});flushEngine();});}

async function getJson(url){const r=await fetch(url);if(!r.ok) throw new Error(`HTTP ${r.status}: ${url}`);return r.json();}
async function loadData(username){const stats=await getJson(`${BASE}/${username}/stats`);const idx=await getJson(`${BASE}/${username}/games/archives`);const months=await Promise.all((idx.archives||[]).map(getJson));return {stats,games:months.flatMap(m=>m.games||[])};}
function parseMovesFromPgn(pgn){if(!pgn) return [];const s=pgn.replace(/\{[^}]*\}|\([^)]*\)|\[[^\]]*\]|\d+\.(\.\.)?|\$\d+|1-0|0-1|1\/2-1\/2|\*/g,' ').trim();return s.split(/\s+/).filter(Boolean)}
function gamePerspective(g,u){const meWhite=g.white.username?.toLowerCase()===u.toLowerCase();const me=meWhite?g.white:g.black,opp=meWhite?g.black:g.white,res=me.result,outcome=res==='win'?'Win':(DRAW_RESULTS.has(res)?'Draw':'Loss');return {meWhite,me,opp,result:res,outcome}}
function analyze(stats,games,u){const rated=games.filter(g=>g.rated&&g.time_class),groups={},byMonth={};let wins=0,losses=0,draws=0;for(const g of rated){const {me,opp,result}=gamePerspective(g,u),tc=g.time_class,key=byMonthKey(g.end_time);if(!groups[tc])groups[tc]={games:0,wins:0,draws:0,losses:0,oppRatingSum:0,myRatingSum:0};const grp=groups[tc];grp.games++;grp.oppRatingSum+=(opp.rating||0);grp.myRatingSum+=(me.rating||0);if(!byMonth[key])byMonth[key]={games:0,wins:0,draws:0,losses:0,avgRating:0,avgOpp:0,n:0};const m=byMonth[key];m.games++;m.n++;m.avgRating+=(me.rating||0);m.avgOpp+=(opp.rating||0);if(result==='win'){wins++;grp.wins++;m.wins++;}else if(DRAW_RESULTS.has(result)){draws++;grp.draws++;m.draws++;}else{losses++;grp.losses++;m.losses++;}}Object.values(byMonth).forEach(m=>{m.avgRating/=m.n;m.avgOpp/=m.n});return {totalGames:rated.length,wins,draws,losses,winRate:rated.length?wins/rated.length:0,rapid:stats.chess_rapid?.last?.rating||null,blitz:stats.chess_blitz?.last?.rating||null,bullet:stats.chess_bullet?.last?.rating||null,byMonth,groups}}
function renderKPIs(a){const k=[['Rated games',a.totalGames],['Wins / Draws / Losses',`${a.wins}/${a.draws}/${a.losses}`],['Win rate',fmtPct(a.winRate)],['Rapid rating',a.rapid??'n/a'],['Blitz rating',a.blitz??'n/a'],['Bullet rating',a.bullet??'n/a']];document.getElementById('kpis').innerHTML=k.map(([x,v])=>`<div class="card"><div class="k">${x}</div><div class="v">${v}</div></div>`).join('')}
function renderCharts(a){const labels=Object.keys(a.byMonth).sort(),r=labels.map(x=>a.byMonth[x].avgRating.toFixed(1)),o=labels.map(x=>a.byMonth[x].avgOpp.toFixed(1)),g=labels.map(x=>a.byMonth[x].games),w=labels.map(x=>a.byMonth[x].wins),d=labels.map(x=>a.byMonth[x].draws),lo=labels.map(x=>a.byMonth[x].losses);for(const c of Object.values(charts)) c.destroy();charts.rating=new Chart(ratingChart,{type:'line',data:{labels,datasets:[{label:'Your avg rating',data:r,borderColor:'#6ea8ff'},{label:'Opponent avg rating',data:o,borderColor:'#f9ae57'}]}});charts.volume=new Chart(volumeChart,{type:'bar',data:{labels,datasets:[{label:'Games played',data:g,backgroundColor:'#6ea8ff'}]}});charts.result=new Chart(resultChart,{type:'line',data:{labels,datasets:[{label:'Wins',data:w,borderColor:'#5bd18b'},{label:'Draws',data:d,borderColor:'#e8ebff'},{label:'Losses',data:lo,borderColor:'#ff7c8f'}]}});charts.opp=new Chart(oppRatingChart,{type:'line',data:{labels,datasets:[{label:'Opponent avg rating trend',data:o,borderColor:'#f9ae57'}]}})}
function renderTimeControlTable(groups){const rows=Object.entries(groups).sort((a,b)=>b[1].games-a[1].games).map(([tc,g])=>`<tr><td>${tc}</td><td>${g.games}</td><td>${fmtPct(g.games?g.wins/g.games:0)}</td><td>${(g.myRatingSum/g.games).toFixed(1)}</td><td>${(g.oppRatingSum/g.games).toFixed(1)}</td></tr>`).join('');timeControlTable.innerHTML=`<thead><tr><th>Time class</th><th>Games</th><th>Win rate</th><th>Your avg rating</th><th>Opp avg rating</th></tr></thead><tbody>${rows}</tbody>`}

async function evalGame(g,username){const chess=new Chess();const moves=parseMovesFromPgn(g.pgn);const evals=[await evalFen(chess.fen())];const moveRows=[];let myLoss=0,oppLoss=0,myN=0,oppN=0;const {meWhite}=gamePerspective(g,username);
 for(let i=0;i<moves.length;i++){const san=moves[i];const ok=chess.move(san,{sloppy:true});if(!ok) continue;const e=await evalFen(chess.fen());evals.push(e);const prev=evals[evals.length-2],delta=Math.abs(e-prev);const whiteMoved=i%2===0;const meMoved=(meWhite&&whiteMoved)||(!meWhite&&!whiteMoved);if(meMoved){myLoss+=delta;myN++;}else{oppLoss+=delta;oppN++;}moveRows.push({ply:i+1,san,eval:e});document.getElementById('evalStatus').textContent=`Analyzed move ${i+1}/${moves.length}`;}
 const toRating=loss=>Math.max(0,Math.min(100,100-loss/20));
 return {moveRows,evals,myQuality:toRating(myN?myLoss/myN:0),oppQuality:toRating(oppN?oppLoss/oppN:0)};
}
function renderEvalChart(evals){if(detailCharts.eval) detailCharts.eval.destroy();detailCharts.eval=new Chart(document.getElementById('evalChart'),{type:'line',data:{labels:evals.map((_,i)=>i),datasets:[{label:'Eval (cp, White +)',data:evals,borderColor:'#6ea8ff'}]},options:{scales:{y:{min:-1000,max:1000}}}})}

function renderGameFeed(games,username,filter){const filtered=games.filter(g=>g.end_time>=getFilterStart(filter)).sort((a,b)=>b.end_time-a.end_time);feedCount.textContent=`${filtered.length} games`;gamesFeed.innerHTML=filtered.map((g,idx)=>{const {me,opp,outcome}=gamePerspective(g,username);const dt=new Date(g.end_time*1000).toISOString().slice(0,10);return `<button class="game-row" data-idx="${idx}"><span>${dt}</span><span>${g.time_class}</span><span>${me.username} (${me.rating}) vs ${opp.username} (${opp.rating})</span><span class="${outcome.toLowerCase()}">${outcome}</span></button>`}).join('')||'<div class="sub">No games in this period.</div>';
 document.querySelectorAll('.game-row').forEach(btn=>btn.addEventListener('click',async()=>{const g=filtered[Number(btn.dataset.idx)];const p=gamePerspective(g,username);gameDetails.innerHTML=`<h4>${p.outcome} • ${g.time_class} • ${new Date(g.end_time*1000).toUTCString()}</h4><div id="evalStatus" class="sub">Running engine eval...</div><canvas id="evalChart"></canvas><div id="quality" class="sub"></div><table><thead><tr><th>#</th><th>Move</th><th>Eval cp</th></tr></thead><tbody id="movesT"></tbody></table>`;const x=await evalGame(g,username);quality.textContent=`Engine quality rating — You: ${x.myQuality.toFixed(1)}/100, Opponent: ${x.oppQuality.toFixed(1)}/100`;movesT.innerHTML=x.moveRows.map(m=>`<tr><td>${m.ply}</td><td>${m.san}</td><td>${m.eval}</td></tr>`).join('');evalStatus.textContent='Engine eval complete.';renderEvalChart(x.evals);}));}

let cache={username:null,stats:null,games:[]};
async function run(){const username=document.getElementById('username').value.trim();const filter=rangeFilter.value;status.textContent='Loading data from Chess.com...';try{if(cache.username!==username||!cache.games.length){cache={username,...await loadData(username)}}const a=analyze(cache.stats,cache.games,username);renderKPIs(a);renderCharts(a);renderTimeControlTable(a.groups);renderGameFeed(cache.games.filter(g=>g.rated&&g.time_class),username,filter);status.textContent=`Loaded ${a.totalGames} rated games for ${username}. Click a game to run full engine eval.`;}catch(e){status.textContent=`Error: ${e.message}`;}}
loadBtn.addEventListener('click',run);rangeFilter.addEventListener('change',run);run();
