"""Launch a Cloudflare quick tunnel that exposes the local backend over HTTPS.

Spawns cloudflared detached, parses the assigned trycloudflare.com URL from
its log, writes it to backend/data/tunnel.url + tunnel.json in the repo root,
and (if the URL changed) commits + pushes tunnel.json so the GitHub Pages
frontend auto-discovers the new backend URL.

Idempotent: re-running it stops the previous tunnel cleanly.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLOUDFLARED = REPO / "backend" / "bin" / "cloudflared.exe"
LOG_DIR = REPO / "backend" / "data"
LOG_DIR.mkdir(parents=True, exist_ok=True)
TUNNEL_LOG = LOG_DIR / "tunnel.log"
TUNNEL_URL_FILE = LOG_DIR / "tunnel.url"
TUNNEL_PID_FILE = LOG_DIR / "tunnel.pid"
TUNNEL_JSON = REPO / "tunnel.json"

LOCAL_BACKEND = "http://localhost:8787"
URL_PATTERN = re.compile(r"https://[a-z0-9-]+\.trycloudflare\.com")


def stop_previous() -> None:
    if not TUNNEL_PID_FILE.exists():
        return
    try:
        pid = int(TUNNEL_PID_FILE.read_text().strip())
    except Exception:
        TUNNEL_PID_FILE.unlink(missing_ok=True)
        return
    print(f"stopping previous tunnel pid={pid}")
    subprocess.run(["taskkill", "/PID", str(pid), "/F", "/T"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    TUNNEL_PID_FILE.unlink(missing_ok=True)


def launch_tunnel() -> int:
    if not CLOUDFLARED.exists():
        print(f"ERROR: missing {CLOUDFLARED}", file=sys.stderr)
        sys.exit(1)
    # Truncate log so URL parser sees only this session's lines
    TUNNEL_LOG.write_text("")

    if os.name == "nt":
        DETACHED_PROCESS = 0x00000008
        CREATE_NEW_PROCESS_GROUP = 0x00000200
        flags = DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP
    else:
        flags = 0

    cmd = [
        str(CLOUDFLARED),
        "tunnel",
        "--no-autoupdate",
        "--url", LOCAL_BACKEND,
        "--logfile", str(TUNNEL_LOG),
        "--loglevel", "info",
    ]
    proc = subprocess.Popen(
        cmd, cwd=str(REPO),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL,
        creationflags=flags if os.name == "nt" else 0,
        close_fds=True, start_new_session=os.name != "nt",
    )
    TUNNEL_PID_FILE.write_text(str(proc.pid))
    return proc.pid


def wait_for_url(timeout_secs: int = 60) -> str | None:
    deadline = time.time() + timeout_secs
    while time.time() < deadline:
        try:
            text = TUNNEL_LOG.read_text(errors="replace") if TUNNEL_LOG.exists() else ""
        except Exception:
            text = ""
        m = URL_PATTERN.search(text)
        if m:
            return m.group(0)
        time.sleep(1.0)
    return None


def read_remote_tunnel_url() -> str | None:
    """Return the URL currently committed in remote tunnel.json, if any."""
    try:
        r = subprocess.run(
            ["git", "show", "origin/main:tunnel.json"],
            cwd=str(REPO), capture_output=True, text=True, check=False,
        )
        if r.returncode != 0:
            return None
        return json.loads(r.stdout).get("backendUrl")
    except Exception:
        return None


def write_local_state(url: str) -> None:
    TUNNEL_URL_FILE.write_text(url)
    payload = {
        "backendUrl": url,
        "updated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z") or time.strftime("%Y-%m-%dT%H:%M:%S"),
        "note": "Auto-generated by scripts/launch_tunnel.py. URL rotates each tunnel restart.",
    }
    TUNNEL_JSON.write_text(json.dumps(payload, indent=2) + "\n")


def commit_and_push_if_changed(url: str) -> bool:
    remote_url = read_remote_tunnel_url()
    if remote_url == url:
        print(f"tunnel.json already up to date on origin/main ({url})")
        return False
    env = os.environ.copy()
    env["GIT_AUTHOR_NAME"] = env.get("GIT_AUTHOR_NAME", "jst28323-art")
    env["GIT_AUTHOR_EMAIL"] = env.get("GIT_AUTHOR_EMAIL", "jst28323@gmail.com")
    env["GIT_COMMITTER_NAME"] = env["GIT_AUTHOR_NAME"]
    env["GIT_COMMITTER_EMAIL"] = env["GIT_AUTHOR_EMAIL"]
    subprocess.run(["git", "fetch", "origin", "main", "--quiet"], cwd=str(REPO), env=env, check=False)
    subprocess.run(["git", "add", "tunnel.json"], cwd=str(REPO), env=env, check=False)
    r = subprocess.run(
        ["git", "commit", "-m", f"chore(tunnel): publish backend URL {url}"],
        cwd=str(REPO), env=env, capture_output=True, text=True, check=False,
    )
    if r.returncode != 0 and "nothing to commit" in (r.stdout + r.stderr).lower():
        print("nothing to commit")
        return False
    elif r.returncode != 0:
        print("commit failed:", r.stdout, r.stderr, file=sys.stderr)
        return False
    p = subprocess.run(["git", "push", "origin", "main"], cwd=str(REPO),
                       env=env, capture_output=True, text=True, check=False)
    if p.returncode != 0:
        print("push failed:", p.stdout, p.stderr, file=sys.stderr)
        return False
    print("pushed tunnel.json")
    return True


def main() -> None:
    stop_previous()
    pid = launch_tunnel()
    print(f"cloudflared launched detached pid={pid}; waiting for URL...")
    url = wait_for_url(60)
    if not url:
        print("ERROR: did not see a trycloudflare URL in the log within 60s", file=sys.stderr)
        print(f"check log: {TUNNEL_LOG}", file=sys.stderr)
        sys.exit(2)
    print(f"tunnel URL: {url}")
    write_local_state(url)
    commit_and_push_if_changed(url)
    print("\nDone. The dashboard at https://jst28323-art.github.io/chess-stats/")
    print("will auto-discover this backend URL on its next reload.")


if __name__ == "__main__":
    main()
